using Microsoft.Extensions.Logging;
using System.Text;
using System.Text.RegularExpressions;

namespace Mvp.Cli.Services;

public class AngularLibraryGeneratorService : IAngularLibraryGeneratorService
{
    private readonly ILogger<AngularLibraryGeneratorService> _logger;

    public AngularLibraryGeneratorService(ILogger<AngularLibraryGeneratorService> logger)
    {
        _logger = logger;
    }

    public Task GenerateAsync(string name, string outputPath, string libraryName, CancellationToken cancellationToken = default)
    {
        _logger.LogInformation("Generating Angular {LibraryName} library: {Name}", libraryName, name);

        var libraryDirectory = Path.Combine(outputPath, $"{name}.{libraryName}");
        var sourceDirectory = Path.Combine(libraryDirectory, "src", "lib");

        Directory.CreateDirectory(sourceDirectory);
        File.WriteAllText(Path.Combine(libraryDirectory, "README.md"), $"# {name}.{libraryName}\n\nAngular library generated by mvp CLI.\n");

        switch (libraryName)
        {
            case "Api":
                GenerateServiceLibrary(sourceDirectory, "api", $"{name}Api");
                break;
            case "Domain":
                GenerateServiceLibrary(sourceDirectory, "domain", $"{name}Domain");
                break;
            case "Components":
                GenerateComponentLibrary(sourceDirectory, name);
                break;
            default:
                throw new InvalidOperationException($"Unsupported Angular library type: {libraryName}");
        }

        _logger.LogInformation("Successfully generated Angular {LibraryName} library: {ProjectName}", libraryName, $"{name}.{libraryName}");
        return Task.CompletedTask;
    }

    private static void GenerateServiceLibrary(string sourceDirectory, string serviceFileBaseName, string typePrefix)
    {
        File.WriteAllText(Path.Combine(sourceDirectory, $"{serviceFileBaseName}.service.contract.ts"), GetServiceContract(typePrefix));
        File.WriteAllText(Path.Combine(sourceDirectory, $"{serviceFileBaseName}.service.ts"), GetService(typePrefix, serviceFileBaseName));
        File.WriteAllText(Path.Combine(sourceDirectory, "public-api.ts"), $"export * from './{serviceFileBaseName}.service';\nexport * from './{serviceFileBaseName}.service.contract';\n");
    }

    private static void GenerateComponentLibrary(string sourceDirectory, string name)
    {
        var componentName = $"{ToKebabCase(name)}-card";
        var componentTypeName = ToPascalCase(componentName);
        var componentDirectory = Path.Combine(sourceDirectory, componentName);

        Directory.CreateDirectory(componentDirectory);
        File.WriteAllText(Path.Combine(componentDirectory, $"{componentName}.component.ts"), GetComponentTypeScript(componentTypeName, componentName));
        File.WriteAllText(Path.Combine(componentDirectory, $"{componentName}.component.html"), "<section class=\"card\"></section>\n");
        File.WriteAllText(Path.Combine(componentDirectory, $"{componentName}.component.scss"), ".card {\n  display: block;\n}\n");
        File.WriteAllText(Path.Combine(sourceDirectory, "public-api.ts"), $"export * from './{componentName}/{componentName}.component';\n");
    }

    private static string GetServiceContract(string typePrefix) => $$"""
        import { InjectionToken } from '@angular/core';

        export interface I{{typePrefix}}Service {
        }

        export const {{typePrefix.ToUpperInvariant()}}_SERVICE = new InjectionToken<I{{typePrefix}}Service>('{{typePrefix}}_SERVICE');
        """;

    private static string GetService(string typePrefix, string serviceFileBaseName) => $$"""
        import { Injectable } from '@angular/core';
        import { I{{typePrefix}}Service } from './{{serviceFileBaseName}}.service.contract';

        @Injectable({ providedIn: 'root' })
        export class {{typePrefix}}Service implements I{{typePrefix}}Service {
        }
        """;

    private static string GetComponentTypeScript(string componentTypeName, string componentName) => $$"""
        import { Component } from '@angular/core';

        @Component({
          selector: 'lib-{{componentName}}',
          templateUrl: './{{componentName}}.component.html',
          styleUrl: './{{componentName}}.component.scss'
        })
        export class {{componentTypeName}}Component {
        }
        """;

    private static string ToPascalCase(string value)
    {
        var words = Regex.Matches(value, "[A-Za-z0-9]+")
            .Select(match => match.Value)
            .Where(word => !string.IsNullOrWhiteSpace(word))
            .Select(word => char.ToUpperInvariant(word[0]) + word[1..].ToLowerInvariant());

        var builder = new StringBuilder();
        foreach (var word in words)
            builder.Append(word);

        return builder.ToString();
    }

    private static string ToKebabCase(string value)
    {
        var normalizedValue = Regex.Replace(value, "([a-z0-9])([A-Z])", "$1-$2");
        normalizedValue = Regex.Replace(normalizedValue, "[^A-Za-z0-9]+", "-");
        return normalizedValue.Trim('-').ToLowerInvariant();
    }
}
