using Microsoft.Extensions.Logging;

namespace Mvp.Cli.Services;

public class AppGeneratorService : IAppGeneratorService
{
    private readonly IProcessRunner _processRunner;
    private readonly ILogger<AppGeneratorService> _logger;

    public AppGeneratorService(IProcessRunner processRunner, ILogger<AppGeneratorService> logger)
    {
        _processRunner = processRunner;
        _logger = logger;
    }

    public async Task GenerateAsync(string name, string outputPath, CancellationToken cancellationToken = default)
    {
        _logger.LogInformation("Generating Angular application: {Name}", name);

        var appDir = Path.Combine(outputPath, $"{name}.App");

        if (await IsAngularCliAvailableAsync(cancellationToken))
        {
            await GenerateWithAngularCliAsync(name, outputPath, appDir, cancellationToken);
        }
        else
        {
            _logger.LogWarning("Angular CLI (ng) not found. Creating minimal Angular project structure.");
            GenerateMinimalAngularStructure(name, appDir);
        }

        _logger.LogInformation("Successfully generated Angular application: {Name}.App", name);
    }

    private async Task<bool> IsAngularCliAvailableAsync(CancellationToken cancellationToken)
    {
        try
        {
            var exitCode = await _processRunner.RunAsync("ng", "version", cancellationToken: cancellationToken);
            return exitCode == 0;
        }
        catch
        {
            return false;
        }
    }

    private async Task GenerateWithAngularCliAsync(string name, string outputPath, string appDir, CancellationToken cancellationToken)
    {
        var exitCode = await _processRunner.RunAsync(
            "ng",
            $"new {name}.App --directory {name}.App --routing true --style scss --skip-git --skip-install",
            outputPath,
            cancellationToken);

        if (exitCode != 0)
            throw new InvalidOperationException($"Failed to create Angular application '{name}.App'. Exit code: {exitCode}");
    }

    private static void GenerateMinimalAngularStructure(string name, string appDir)
    {
        Directory.CreateDirectory(appDir);
        Directory.CreateDirectory(Path.Combine(appDir, "src", "app"));
        Directory.CreateDirectory(Path.Combine(appDir, "src", "assets"));
        Directory.CreateDirectory(Path.Combine(appDir, "src", "environments"));

        File.WriteAllText(Path.Combine(appDir, "package.json"), GetPackageJson(name));
        File.WriteAllText(Path.Combine(appDir, "tsconfig.json"), GetTsConfig());
        File.WriteAllText(Path.Combine(appDir, "angular.json"), GetAngularJson(name));
        File.WriteAllText(Path.Combine(appDir, "src", "main.ts"), GetMainTs());
        File.WriteAllText(Path.Combine(appDir, "src", "index.html"), GetIndexHtml(name));
        File.WriteAllText(Path.Combine(appDir, "src", "styles.scss"), "/* Global styles */\n");
        File.WriteAllText(Path.Combine(appDir, "src", "app", "app.component.ts"), GetAppComponentTs(name));
        File.WriteAllText(Path.Combine(appDir, "src", "app", "app.component.html"), GetAppComponentHtml(name));
        File.WriteAllText(Path.Combine(appDir, "src", "app", "app.module.ts"), GetAppModuleTs());
        File.WriteAllText(Path.Combine(appDir, "src", "app", "app-routing.module.ts"), GetAppRoutingModuleTs());
        File.WriteAllText(Path.Combine(appDir, "src", "environments", "environment.ts"), GetEnvironmentTs());
        File.WriteAllText(Path.Combine(appDir, "src", "environments", "environment.prod.ts"), GetEnvironmentProdTs());
        File.WriteAllText(Path.Combine(appDir, ".gitignore"), GetGitIgnore());
        File.WriteAllText(Path.Combine(appDir, "README.md"), $"# {name}.App\n\nAngular application generated by mvp CLI.\n");
    }

    private static string GetPackageJson(string name) => $$"""
        {
          "name": "{{name.ToLower()}}-app",
          "version": "0.0.0",
          "scripts": {
            "ng": "ng",
            "start": "ng serve",
            "build": "ng build",
            "watch": "ng build --watch --configuration development",
            "test": "ng test"
          },
          "dependencies": {
            "@angular/animations": "^19.0.0",
            "@angular/common": "^19.0.0",
            "@angular/compiler": "^19.0.0",
            "@angular/core": "^19.0.0",
            "@angular/forms": "^19.0.0",
            "@angular/platform-browser": "^19.0.0",
            "@angular/platform-browser-dynamic": "^19.0.0",
            "@angular/router": "^19.0.0",
            "rxjs": "~7.8.0",
            "tslib": "^2.3.0",
            "zone.js": "~0.14.0"
          },
          "devDependencies": {
            "@angular-devkit/build-angular": "^19.0.0",
            "@angular/cli": "^19.0.0",
            "@angular/compiler-cli": "^19.0.0",
            "@types/jasmine": "~5.1.0",
            "jasmine-core": "~5.1.0",
            "karma": "~6.4.0",
            "karma-chrome-launcher": "~3.2.0",
            "karma-coverage": "~2.2.0",
            "karma-jasmine": "~5.1.0",
            "karma-jasmine-html-reporter": "~2.1.0",
            "typescript": "~5.6.0"
          }
        }
        """;

    private static string GetTsConfig() => """
        {
          "compileOnSave": false,
          "compilerOptions": {
            "baseUrl": "./",
            "outDir": "./dist/out-tsc",
            "forceConsistentCasingInFileNames": true,
            "strict": true,
            "noImplicitOverride": true,
            "noPropertyAccessFromIndexSignature": true,
            "noImplicitReturns": true,
            "noFallthroughCasesInSwitch": true,
            "sourceMap": true,
            "declaration": false,
            "downlevelIteration": true,
            "experimentalDecorators": true,
            "moduleResolution": "node",
            "importHelpers": true,
            "target": "ES2022",
            "module": "ES2022",
            "useDefineForClassFields": false,
            "lib": ["ES2022", "dom"]
          },
          "angularCompilerOptions": {
            "enableI18nLegacyMessageIdFormat": false,
            "strictInjectionParameters": true,
            "strictInputAccessModifiers": true,
            "strictTemplates": true
          }
        }
        """;

    private static string GetAngularJson(string name) => $$"""
        {
          "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
          "version": 1,
          "newProjectRoot": "projects",
          "projects": {
            "{{name.ToLower()}}-app": {
              "projectType": "application",
              "schematics": {
                "@schematics/angular:component": { "style": "scss" }
              },
              "root": "",
              "sourceRoot": "src",
              "prefix": "app",
              "architect": {
                "build": {
                  "builder": "@angular-devkit/build-angular:browser",
                  "options": {
                    "outputPath": "dist/{{name.ToLower()}}-app",
                    "index": "src/index.html",
                    "main": "src/main.ts",
                    "polyfills": ["zone.js"],
                    "tsConfig": "tsconfig.json",
                    "styles": ["src/styles.scss"],
                    "scripts": []
                  }
                },
                "serve": {
                  "builder": "@angular-devkit/build-angular:dev-server",
                  "configurations": {
                    "production": { "buildTarget": "{{name.ToLower()}}-app:build:production" },
                    "development": { "buildTarget": "{{name.ToLower()}}-app:build:development" }
                  },
                  "defaultConfiguration": "development"
                }
              }
            }
          }
        }
        """;

    private static string GetMainTs() => """
        import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
        import { AppModule } from './app/app.module';

        platformBrowserDynamic().bootstrapModule(AppModule)
          .catch(err => console.error(err));
        """;

    private static string GetIndexHtml(string name) => $$"""
        <!doctype html>
        <html lang="en">
        <head>
          <meta charset="utf-8">
          <title>{{name}}</title>
          <base href="/">
          <meta name="viewport" content="width=device-width, initial-scale=1">
          <link rel="icon" type="image/x-icon" href="favicon.ico">
        </head>
        <body>
          <app-root></app-root>
        </body>
        </html>
        """;

    private static string GetAppComponentTs(string name) => $$"""
        import { Component } from '@angular/core';

        @Component({
          selector: 'app-root',
          templateUrl: './app.component.html'
        })
        export class AppComponent {
          title = '{{name}}';
        }
        """;

    private static string GetAppComponentHtml(string name) => $$"""
        <main>
          <h1>Welcome to {{name}}!</h1>
          <router-outlet></router-outlet>
        </main>
        """;

    private static string GetAppModuleTs() => """
        import { NgModule } from '@angular/core';
        import { BrowserModule } from '@angular/platform-browser';
        import { AppRoutingModule } from './app-routing.module';
        import { AppComponent } from './app.component';

        @NgModule({
          declarations: [AppComponent],
          imports: [BrowserModule, AppRoutingModule],
          providers: [],
          bootstrap: [AppComponent]
        })
        export class AppModule {}
        """;

    private static string GetAppRoutingModuleTs() => """
        import { NgModule } from '@angular/core';
        import { RouterModule, Routes } from '@angular/router';

        const routes: Routes = [];

        @NgModule({
          imports: [RouterModule.forRoot(routes)],
          exports: [RouterModule]
        })
        export class AppRoutingModule {}
        """;

    private static string GetEnvironmentTs() => """
        export const environment = {
          production: false,
          apiUrl: 'https://localhost:5001'
        };
        """;

    private static string GetEnvironmentProdTs() => """
        export const environment = {
          production: true,
          apiUrl: ''
        };
        """;

    private static string GetGitIgnore() => """
        # Dependencies
        node_modules/

        # Build output
        dist/
        tmp/
        out-tsc/

        # Misc
        .angular/
        .editorconfig
        .browserslistrc
        """;
}
